"""initial schema

Revision ID: 0889b360cf1c
Revises: 
Create Date: 2026-04-11 12:51:25.867825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0889b360cf1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codon_table_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organism_tax_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('table_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codon_table_cache_organism_tax_id'), 'codon_table_cache', ['organism_tax_id'], unique=False)
    op.create_table('organisms',
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('lineage', sa.Text(), nullable=True),
    sa.Column('gc_content', sa.Float(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tax_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constructs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_sequence', sa.Text(), nullable=True),
    sa.Column('organism_tax_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('construct_elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('construct_id', sa.Uuid(), nullable=False),
    sa.Column('element_type', sa.Enum('PROMOTER', 'KOZAK', 'CDS', 'TERMINATOR', 'TAG', 'UTR', 'CUSTOM', name='elementtype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('construct_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('input_sequence', sa.Text(), nullable=False),
    sa.Column('output_sequence', sa.Text(), nullable=True),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cai_before', sa.Float(), nullable=True),
    sa.Column('cai_after', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_jobs')
    op.drop_table('construct_elements')
    op.drop_table('constructs')
    op.drop_table('projects')
    op.drop_table('organisms')
    op.drop_index(op.f('ix_codon_table_cache_organism_tax_id'), table_name='codon_table_cache')
    op.drop_table('codon_table_cache')
    # ### end Alembic commands ###
