"""add_session_id_to_projects_and_jobs

Revision ID: 6feead7f089f
Revises: 0889b360cf1c
Create Date: 2026-04-11 14:45:40.660437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6feead7f089f'
down_revision: Union[str, None] = '0889b360cf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column('projects', sa.Column('session_id', sa.String(length=36), nullable=True))
    op.add_column('optimization_jobs', sa.Column('session_id', sa.String(length=36), nullable=True))

    # Backfill existing rows with a legacy sentinel
    op.execute("UPDATE projects SET session_id = 'legacy-00000000-0000-0000-0000' WHERE session_id IS NULL")
    op.execute("UPDATE optimization_jobs SET session_id = 'legacy-00000000-0000-0000-0000' WHERE session_id IS NULL")

    # Make non-nullable
    op.alter_column('projects', 'session_id', nullable=False)
    op.alter_column('optimization_jobs', 'session_id', nullable=False)

    # Create indexes
    op.create_index(op.f('ix_projects_session_id'), 'projects', ['session_id'], unique=False)
    op.create_index(op.f('ix_optimization_jobs_session_id'), 'optimization_jobs', ['session_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_session_id'), table_name='projects')
    op.drop_column('projects', 'session_id')
    op.drop_index(op.f('ix_optimization_jobs_session_id'), table_name='optimization_jobs')
    op.drop_column('optimization_jobs', 'session_id')
    # ### end Alembic commands ###
